name: Variable Scope Demo

env:
  MY_WORKFLOW_VARIABLE: "This is a workflow-level variable"

on:
  push:

jobs:
  demo-job:
    env:
      MY_JOB_VARIABLE: "This is a job-level variable"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Workflow and Job Level Variables
        run: |
          echo "Workflow Variable: $MY_WORKFLOW_VARIABLE"
          echo "Job Variable: $MY_JOB_VARIABLE"

      - name: Use Step-Level Variable
        env:
          MY_STEP_VARIABLE: "This is a step-level variable"
        run: |
          echo "Step Variable: $MY_STEP_VARIABLE"
          echo "Workflow Variable: $MY_WORKFLOW_VARIABLE"
          echo "Job Variable: $MY_JOB_VARIABLE"

